@echo off
echo Killing old processes on port 3000...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :3000 ^| findstr LISTENING') do taskkill /F /PID %%a >nul 2>&1
if exist apps\web\.next\dev\lock del apps\web\.next\dev\lock >nul 2>&1
echo Starting dev server...
pnpm dev
